name: Deploy to Gigalixir

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Elixir
      run: |
        sudo apt-get install -y curl git
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
        echo ". $HOME/.asdf/asdf.sh" >> ~/.bashrc
        echo ". $HOME/.asdf/completions/asdf.bash" >> ~/.bashrc
        . $HOME/.asdf/asdf.sh
        asdf plugin add erlang
        asdf plugin add elixir
        asdf install erlang 25.2
        asdf install elixir 1.13.4
        asdf global erlang 25.2
        asdf global elixir 1.13.4

    - name: Build and test
      run: |
        cd $GITHUB_WORKSPACE
        mix local.hex --force
        mix deps.get
        mix test
        
    - name: Install Gigalixir CLI
      run: |
        sudo apt-get install -y python3 python3-pip
        pip3 install gigalixir
        
    - name: Deploy to Gigalixir
      env:
        GIGALIXIR_EMAIL: ${{ secrets.GIGALIXIR_EMAIL }}
        GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
        GIGALIXIR_APP_NAME: ${{ secrets.GIGALIXIR_APP_NAME }}
      run: |
        gigalixir login -e "$GIGALIXIR_EMAIL" -p "$GIGALIXIR_PASSWORD" -y
        gigalixir git:remote $GIGALIXIR_APP_NAME
        git push -f gigalixir HEAD:refs/heads/main
